### PR TITLE
feature/congrats happy programmer day:)

### PR DESCRIPTION
**Pull request by Nadya101**
Happy programmer day! :)

### CODE REVIEW

**Comment by nickrograch** [comment]
.........|/|/|/|/|/|/|
                                                      ............(^O.O^)
                                                      ...........(...(_)...)
                                                      ............\..--../_
                                                      ............./??Y??\.\
                                                      .........|....|.......\..\
                                                      .........|._.\_.......|\_.\
                                                      ..........\__\......|...\..\
                                                      ......(???\...\_|/??\__\_________oooooo
                                                      ........)===????====0000=========)
                                                      ......(____/???\__/--------------oooooo
                                                      ........./..../......\...\
                                                      ..__./._/.............\._.\__
                                                      (____ /................(_____)

                                                                    ____________________$$$$$$$$$$_____________
                                                                    __________________$$$$$$$$$$$$$$___________
                                                                    _________________$$$$$$____$$$$$___________
                                                                    ________________$$$$$________$$$$__________
                                                                    _______________$$$$$_________$$$$__________
                                                                    _______________$$$$__$$$$$$$$$$$$$$$$$_____
                                                                    ______________$$$$___$$$$$$$$$$$$$$$$$$_____
                                                                    _____________$$$$$___$$_______$$____$$$_____
                                                                    $$$$_________$$$$____$$_______$$____$$$_____
                                                                    $$$$________$$$$$____$$_______$$____$$$_____
                                                                    $$$$$_____$$$$$$_____$$$$$$$$$$$$$$$$$$_____
                                                                    _$$$$$$$$$$$$$$______$$_____________$$$_____
                                                                    ___$$$$$$$$$$________$$_____________$$$_____
                                                                    _____$$$$$$__________$$_____________$$$_____
                                                                    _____________________$$_____________$$$_____
                                                                    _____________________$$_____________$$$_____
                                                                    _____________________$$_____________$$$_____
                                                                    _____________________$$_____________$$$_____
                                                                    _____________________$$_____________$$$_____
                                                                    _____________________$$_____________$$$_____
                                                                    _____________________$$$____________$$$_____
                                                                    _____________________$$$$__________$$$______
                                                                    ______________________$$$$________$$$$______
                                                                    _______________________$$$$$$_$$$$$$$_______
                                                                    _________________________$$$$$$$$$$_________
                                                                    ____________________________________________



                                  =====================================,=====,======,
                                  =====================================`$,====$,====`$,=======;
                                  ======================================`$+===`$,===`$,======d;=====,
                                  =======================================`$b,==`$,====$$,====d$====,$
                                  ========================================`$$+==l$+==;$$$===d$$===,$'
                                  =#####===##==##==##==##==##==##==========`$$b,;$$b,$$$$$$;=,d$$===,$
                                  =##==##==##==##==###=##==##=##============`$$$b$$$$$$$$$$$$$$$;=,d$'
                                  =##==##==##==##==######==####==============`$$$+""""~~""^¦$$$$$$$$P,,
                                  =#####===##==##==##=###==##=##=============^==============~^"$$$$;,s$$"
                                  =##=======####===##==##==##==##==========,^=================`$$$$$$'
                                  ========================================,'====================`$$$$$$#;;,,,
                                  ========================================'=====================`$$,y$$@"
                                  =====##==##===####==######=========== =======================`$$$$'
                                  =====###=##==##==##===##=============,^=======,,,=========,,,yyyyy$$#$$$$$#
                                  =====######==##==##===##=============`\,==,,/'^ ``=====`$$$$$$$$$$d;$$$$###~
                                  =====##=###==##==##===##==============/'=,$$"="""-====`$b`?$$$$$$$$$$;$$$b,
                                  =====##==##===####====##=============,'===`^*;-=''====`$$$$$$$#$$$$$$$;$$$¦$b.
                                  =================================== ,,,;,=============`¦$-",¬y+`?$$$$;$b,
                                  ====================================`;==================]$& $';$$$$d$$$b,
                                  =#####===#####===####===#####======,yyy,,================+@@&`'d$$$$d$P;;;¦$,
                                  =##==##==##=====##==##==##==##=====\?`^"$@by,===========~¦>^,$$$$$d$$b,
                                  =##==##==####===##==##==##==##=====,&~`^"¦?~#`========,yb, ,?$$$$$d$$$$b,
                                  =##==##==##=====######==##==##===='===$====,======,,yd$$$$$?•?$$$d$$~~"¦;
                                  =##==##==##=====##==##==##==##===/==='$,=$$$yyyyy$$$$$"=,$$$+$$$d$$$b,
                                  =#####===#####==##==##==#####====`-=##$$$$$$$$$$$$$$^~==,$$$$$$$R$'
                                  ======================================~~"$$$$$$$$$'===,$$$$$$$D$'
                                  ==========================================`#$$$$$'===,$$$`,$$Z$$
                                  ============================================`#$$'===,$@P',$$o$$'
                                  =============================================`'="yd$$P',$$N$P'
                                  ================================================-~~~"+$="

**Comment by nickrograch** [comment]
_____________________________________________
                                            _____________________________________________
                                            ____________1¶1______________________________
                                            ____________¶¶¶1_________11¶¶¶1______________
                                            ___________1¶¶¶¶______11¶¶¶¶¶¶1______________
                                            ___________1¶¶¶¶____1¶¶¶¶¶¶¶1________________
                                            ____________¶¶¶¶1__1¶¶¶¶¶1___________________
                                            1¶¶¶¶¶¶111__1¶¶¶11¶¶¶¶¶11__11111111__________
                                            ¶¶¶¶¶¶¶¶¶¶¶111¶¶1¶¶¶¶111¶¶¶¶¶¶¶¶¶¶¶¶¶¶1_____1
                                            __11111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶11______
                                            _______11¶¶¶¶¶¶¶¶¶¶¶¶11¶¶¶¶¶111______________
                                            _1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶11____________________
                                            ¶¶¶¶¶¶¶¶¶¶1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1_______________111
                                            ¶¶¶¶¶¶1__1¶¶¶¶11¶¶1¶¶111¶¶¶11_________1¶¶¶¶¶¶
                                            1111____1¶¶¶¶¶_1¶¶11¶¶__________________1111¶
                                            ________1¶¶¶11_1¶1__¶¶¶______________________
                                            _______1¶¶¶¶1_______1¶¶¶____________111______
                                            _______1¶¶¶111________¶¶1___1¶¶1___1¶¶1______
                                            _111____1¶¶¶¶¶1_______1¶¶1___1¶¶¶1_¶¶¶_______
                                            _1¶¶¶¶1__1¶¶¶1______11_¶¶¶11111¶¶¶1¶¶111¶¶¶¶1
                                            ___1¶¶¶¶11¶¶¶__1¶¶¶¶¶¶11¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
                                            111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1__1¶¶1__1¶¶¶¶¶¶¶¶¶¶1___
                                            ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1______¶¶¶__1¶¶¶¶¶¶11¶¶¶¶1_
                                            1111_1¶¶¶¶¶¶¶1¶¶¶¶¶¶¶¶1__1¶¶¶¶¶¶1¶¶¶_____111_
                                            ____1¶¶¶¶¶¶¶11____11111___1¶¶¶1__1¶1_11______
                                            ___1¶¶¶__¶¶11¶1___________1¶¶¶___11_111______
                                            __1¶¶¶1__¶¶1_1¶1__________1¶¶¶1_____111______
                                            ___11____11__1¶¶1__________1¶¶¶_____1¶1______
                                            ______________1¶¶1__________¶¶¶1____1¶1______
                                            _______________¶¶¶__________1¶¶¶____1¶1______
                                            ________________¶¶¶1________1¶¶¶1___1¶1_____1
                                            _________________¶¶¶1_______1¶¶¶1___1¶1_____1
                                            __________________¶¶¶1_______1¶¶¶1__1¶¶_____¶
                                            ___________________¶¶¶1__11__1¶¶¶¶1_1¶¶_____¶
                                            ____________________1¶¶11¶¶¶__¶¶¶¶__1¶1____1¶
                                            1__________________11¶¶¶11¶¶¶1¶¶¶¶__¶¶¶____1¶
                                            11________________1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1___1¶
                                            111__________111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
                                            111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
                                            ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
                                            ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
                                            ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
                                            ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
                                            ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
                                            ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶

**Comment by nickrograch** [comment]
__________________111
                                              _______________1111111111
                                              _____________1¶¶¶1___1¶¶¶1
                                              _____________¶¶¶¶1__111¶¶¶
                                              ____________1¶¶¶¶¶__1¶¶¶¶¶¶
                                              _____________1¶11¶1_¶¶¶¶¶¶1
                                              _____________1¶¶1¶1_¶¶1¶¶¶
                                              ______________1¶¶¶1_¶¶¶¶¶1
                                              _______________¶¶¶111¶¶¶1
                                              ______________1¶¶¶¶¶¶¶¶¶¶1
                                              ____________1¶¶¶1___11¶¶¶¶¶1
                                              _________11111¶¶______1¶¶¶¶¶¶1
                                              _____1111111____________111¶¶¶¶¶¶111
                                              __1___11111___11_____1111111111¶11111¶
                                              _1____1111_______11111_______11111111¶¶
                                              ¶1_____111________111_______1111¶¶1111¶
                                              ¶1____1¶111_______111_____111111¶¶1111¶1
                                              1¶¶¶¶¶¶111________1_______1111111¶¶¶¶¶¶1
                                              _¶¶¶¶¶¶11________1111__________1¶¶¶¶¶¶¶
                                              _1¶11¶¶¶¶111111_1¶__¶¶11111111¶¶¶¶¶1¶¶1
                                              __¶___¶¶¶¶¶¶¶¶1_____1¶¶¶1¶¶¶¶¶¶¶¶¶11¶¶
                                              __¶___1¶¶¶¶¶1_______1¶¶¶11¶¶¶¶¶¶¶¶11¶¶
                                              __1¶11¶¶¶¶¶1111_____¶¶¶¶¶¶¶¶¶¶¶¶¶11¶¶¶
                                              ___¶¶¶¶¶¶¶11¶¶¶¶¶¶¶¶1___1¶¶¶¶¶¶¶¶11¶¶
                                              ___1¶¶¶¶¶¶¶¶¶¶¶1__________11¶¶¶¶¶¶¶¶¶
                                              ____1¶¶¶¶1___1¶¶¶¶¶¶¶¶¶¶¶111¶¶¶¶¶¶¶¶
                                              _______1¶¶¶¶¶¶¶111111111¶¶11111¶¶1¶
                                              _________1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
                                              __________¶¶¶111¶¶¶1¶¶¶111¶¶¶¶¶
                                              __________¶¶11111¶¶11¶111111¶¶¶
                                              __________¶¶¶11111¶11¶111111¶¶¶
                                              _________1¶1¶¶1111¶11¶1111¶¶11¶1
                                              _________¶¶11¶¶111¶11¶1111¶111¶¶
                                              _________¶¶111¶¶¶1¶11¶¶¶¶¶1111¶¶
                                              _________¶¶1__11¶¶¶11¶¶¶¶11__1¶¶
                                              _________¶¶1__111¶¶11¶¶111___1¶¶
                                              _________¶¶11_1111¶¶1¶1111__11¶¶
                                              _________1¶¶111111¶¶1¶1111__1¶¶¶
                                              _________1¶¶111111¶¶1¶1111_11¶¶1
                                              __________¶¶1111111¶1¶1111111¶¶
                                              __________¶¶¶111¶1¶¶1¶1111111¶¶
                                              ___________¶¶¶11¶1¶¶11¶11111¶¶1
                                              ____________1¶¶¶¶¶¶¶1¶¶¶¶¶¶¶¶1
                                              _____________¶¶¶¶¶¶¶1¶¶¶¶¶¶¶1
                                              _____________¶¶¶¶¶¶¶1¶¶¶¶¶¶¶1
                                              ____________¶¶¶¶¶¶¶¶1¶¶¶¶1¶¶¶
                                              ____________¶¶¶¶¶¶¶¶1¶¶¶¶¶¶¶¶
                                              ____________¶¶111¶¶¶1¶¶1¶¶¶1¶1
                                              ____________¶¶111¶¶¶1¶¶11111¶¶
                                              ____________¶¶1111¶¶1¶¶11111¶¶
                                              ____________1¶1111¶¶1¶¶11111¶1
                                              _____________¶111¶¶¶1¶¶1111¶¶
                                              _____________¶¶1¶1¶¶1¶¶111¶¶¶
                                              _____________1¶¶¶¶¶¶1¶¶¶11¶¶
                                              ______________¶¶¶1¶¶¶¶¶111¶¶
                                              _______________¶¶111¶¶1111¶1
                                              _______________¶¶1111¶¶11¶¶
                                              ___________111¶¶¶¶¶¶¶¶¶¶1¶¶¶¶11
                                              ______1¶¶¶¶¶¶¶¶¶¶11¶¶¶¶¶11¶¶¶¶¶¶¶¶1
                                              1¶¶¶1111111¶¶¶1_1¶¶¶¶¶¶¶11¶¶¶¶¶¶¶11111¶¶
                                              ¶¶11¶¶¶¶¶¶¶¶1111¶¶¶¶¶¶¶¶¶1¶¶¶1¶¶¶¶¶¶¶¶¶¶
                                              ¶¶¶11111¶¶¶¶111¶¶¶¶¶¶¶¶¶¶11¶¶¶¶¶¶¶11111¶
                                              11¶¶11¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1¶¶¶¶¶¶¶¶¶11¶1
                                              1¶111¶¶11111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶11¶¶1111
                                              ¶¶¶¶¶¶¶¶¶1111¶¶¶¶¶¶¶¶¶¶¶¶¶¶1¶111¶¶¶¶¶¶¶¶
                                              ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
                                              ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶

**Comment by nickrograch** [comment]
______________$$LOVE$$$
                                                            _____________$$$$$$$$$$$_________________________________,,
                                                            _____________$$$$$$$$$$$$______________________________$$$$$,
                                                            _____________`$$$$$$$$$$$____________________________$TERMI$$
                                                            ______________`$$$$$$$$$Z$______uuu_______uuu_______$$$$$$$$"
                                                            _______________`$ZzZ$$$Z$$$___$$$$$$$___$$$$$$$____$$$$$$$$"
                                                            ________________`$$$ZZZ$$$$$_$$$$$$$$$_$$$$$$$$$__$$$$$$$$"
                                                            _________________`$$$$$$$$$$_$$ZZ$$$$$_$$ZZZ$$$$_$$$$$$$$
                                                            ____u$$$$$$u______`$$$$$$$$$$_$$$ZZZ$$_$$$$$ZZ$$_$$$$$$$"
                                                            __$$$$$$$$$$Z$_____`$ZZ$$$ZZZ_$$$$$$$$_$$$$$$$$$_$$$$$$
                                                            _$$$$$$$$$$$Z$$$$__$$$$zzz$$$_$$$$$$$$_$$$$$$$$$_$$$$$$"
                                                            _$$$$$$$$$$Z$$$$$$$$$$$$$$$$$_$$ZZ$$$$_$ZZZ$$$$$_$$$$$"
                                                            ___"$$$$$$$Z$$$$$$$$$$$$$$$$$_$$$$$ZZ$_$ZZZ$$$$$_$$$$$"
                                                            ________`$Z$$$$$$$$$$$$$$$$$$_$SB$$$__$$_$$$$$$_$$$$"
                                                            __________`$$$$$$$$$$$$$$$$$$$,``"`,$$$$,_``"`,$$$$$$$"
                                                            ___________"$$$$$$$$$$$$$$$$$$$$$$_$$$$$$$$$$$$$$$"
                                                            _____________"$$$$$$$$$$$$$$$$$$$$$_$$$$$$$$$$$$$"
                                                            _______________"$$$$$$$$$$$$$$$$$$$_$$$$$$$$$$$$"
                                                            __________________"$$$$$$$$$$$$$$$$_$$$$$$$$$$"
                                                            ___________________"$$$$$$$$$$$$$$$$_

**Review by nickrograch — APPROVED** [review]
здорово, Спасибо) Добавь меня в свой репозиторий, через настройки=)

**Comment by nickrogracher** [comment]
Добавь меня в свой репозиторий, через настройки

**Comment by Nadya101** [comment]
@nickrogracher  вчера отправила запрос) жду подтверждение)

**Pull request closed without merging**
